"use client";
import {useState,useEffect} from "react";
import {ArrowDown,ArrowUpRight,CalendarDays,MapPin,Gift,Check} from "lucide-react";
export default function Home(){
const [status,setStatus]=useState("idle");
useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const controller=new AbortController();Promise.resolve(c.registerTool({name:"open_rsvp_form",description:"Open the RSVP form without submitting a reservation.",inputSchema:{type:"object",properties:{},additionalProperties:false},execute:()=>{document.getElementById("rsvp")?.scrollIntoView();document.getElementById("name")?.focus({preventScroll:true});return {opened:true};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setStatus("saving");try{const r=await fetch("/api/rsvp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(data))});if(!r.ok)throw Error();setStatus("success");}catch{setStatus("error");}}
return <main><header><a className="wordmark" href="#">LOVERTE</a><span className="header-note">ÜKS HOMMIK. AEGA ISEENDALE.</span><a className="header-rsvp" href="#rsvp">Tulen ka <ArrowUpRight size={16}/></a></header>
<section className="hero"><div className="hero-copy"><p className="eyebrow">SINU PÜHAPÄEVANE ILURITUAAL</p><h1>Loverte <span>×</span> Lauren<em>K-Brunch</em></h1><p className="intro">Hei, kaunis. Võta üks hommik iseendale.</p><p className="description">Mõnus brunch, näojooga ja Laureni K-beauty lemmikud. Tule veeda meiega üks rahulik pühapäevahommik.</p><div className="details"><div><CalendarDays size={20}/><span><strong>4. oktoober 2026</strong><small>Pühapäev · 11.00–14.00</small></span></div><div><MapPin size={20}/><span><strong>Blessa Stuudio</strong><small>Vesilennuki 20, Noblessner</small></span></div></div><a className="button" href="#rsvp">Jah, tulen hea meelega <ArrowDown size={18}/></a><p className="dresscode">Dress code: comfy casual. Tule nii, et sul on hea.</p></div><div className="portrait" role="img" aria-label="Lauren valges topis"><div className="portrait-caption">Slow Sunday,<br/><em>glowing skin.</em></div><span className="photo-note">LAURENI ILULEMMIKUD, SINU UUS RITUAAL</span></div></section>
<section className="morning"><div><p className="eyebrow">MIDAGI HEAD SINULE</p><h2>Vähem kiirust.<br/><em>Rohkem head olemist.</em></h2></div><div className="moments"><article><span>01 / NAUDI</span><h3>Aeglane brunch</h3><p>Head maitsed, värske kohv ja mõnusad jutuajamised. Nii algabki üks ilus pühapäev.</p></article><article><span>02 / LÕÕGASTU</span><h3>Näojooga Eveliniga</h3><p>Võtame aja maha ja äratame näolihased koos näojooga juhendaja Evelin Allveega.</p></article><article><span>03 / SÄRA</span><h3>Laureni ilurutiin</h3><p>Avastame koos Laureni Korea ilulemmikud ja proovime tema igapäevast nahahooldusrituaali.</p></article></div></section>
<div className="gift-strip"><Gift size={26} strokeWidth={1.3}/><p>Natuke seda hommikut tuleb sinuga koju.<br/><strong>Laureni ilurutiin on sulle kingituseks.</strong></p><span>WITH LOVE, LOVERTE</span></div>
<section id="rsvp" className="rsvp"><div><p className="eyebrow">KOHTUME K-BRUNCH’IL</p><h2>Üks mõnus hommik.<br/><em>Sina ka?</em></h2><p>Anna meile teada, et oled tulemas.<br/>Me juba ootame sind.</p><a className="location" href="https://blessa.ee/" target="_blank" rel="noreferrer">4. oktoober · Blessa Stuudio <ArrowUpRight size={16}/></a></div><div>{status==="success"?<div className="success" role="status"><Check/><h3>Kohtumiseni, kaunis!</h3><p>Sinu osalemine on kinnitatud.<br/>Ootame sind 4. oktoobril kell 11.00<br/>Blessa Stuudios.</p><a className="button" href="/kbrunch.ics">Lisa kalendrisse <CalendarDays size={18}/></a></div>:<form onSubmit={submit}><label htmlFor="name">Sinu nimi</label><input id="name" name="name" placeholder="Ees- ja perekonnanimi" autoComplete="name" required maxLength={100}/><label htmlFor="email">E-posti aadress</label><input id="email" name="email" type="email" placeholder="sinu@email.ee" autoComplete="email" required maxLength={254}/><label htmlFor="dietary">Toidueelistused või allergiad <span>(valikuline)</span></label><input id="dietary" name="dietary" placeholder="Et saaksime sinuga arvestada" maxLength={500}/><button className="button" disabled={status==="saving"}>{status==="saving"?"Kinnitame…":"Kinnitan osalemise"}<ArrowUpRight size={18}/></button>{status==="error"&&<p role="alert" className="error">Kinnitamine ei õnnestunud. Palun proovi uuesti.</p>}<p className="privacy">Kasutame sinu andmeid ainult selle ürituse korraldamiseks.</p></form>}</div></section><footer><a className="wordmark" href="#">LOVERTE</a><span>Sinule. Sinu nahale. Sinu pühapäevale.</span><span>LOVERTE × LAUREN · 2026</span></footer></main>}
