"use client";
import {useState,useEffect} from "react";
import {ArrowDown,ArrowUpRight,CalendarDays,MapPin,Gift,Check} from "lucide-react";
export default function Home(){
const [status,setStatus]=useState("idle");
useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const controller=new AbortController();Promise.resolve(c.registerTool({name:"open_rsvp_form",description:"Open the RSVP form without submitting a reservation.",inputSchema:{type:"object",properties:{},additionalProperties:false},execute:()=>{document.getElementById("rsvp")?.scrollIntoView();document.getElementById("name")?.focus({preventScroll:true});return {opened:true};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setStatus("saving");try{const r=await fetch("/api/rsvp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(data))});if(!r.ok)throw Error();setStatus("success");}catch{setStatus("error");}}
return <main>
<section className="hero" aria-labelledby="event-title"><header><a href="#" aria-label="Loverte"><img className="logo" src="/loverte-logo.png" alt="Loverte"/></a><a className="header-rsvp" href="#rsvp">Kinnita osalemine <ArrowUpRight size={18}/></a></header><div className="mobile-portrait" role="img" aria-label="Lauren"/><div className="hero-copy"><p className="welcome">Hei, kaunis! Oled väga oodatud</p><h1 id="event-title">Loverte x<br/>Lauren<br/>K-Brunch</h1><div className="details"><p><CalendarDays aria-hidden="true"/><span>4. oktoober 2026 <span className="time">kell 11.00–14.00</span></span></p><p><MapPin aria-hidden="true"/><span>Blessa Stuudio, Noblessner</span></p></div><a className="button hero-button" href="#rsvp">Tulen hea meelega <ArrowDown size={22}/></a></div></section>
<section className="invitation"><p className="eyebrow">PÜHAPÄEV. SINU TEMPOS.</p><h2>Hea seltskond.<br/>Mõnus brunch. Särav nahk.</h2><p className="intro">Võtame koos aja maha. Naudime brunch’i, lõõgastume Evelin Allvee näojoogaga ja avastame Laureni K-beauty ilurutiini.</p><div className="gift-note"><Gift size={23}/><p>Laureni ilurutiin tuleb sinuga koju — kingituseks meilt sulle.</p></div></section>
<section id="rsvp" className="rsvp"><div className="rsvp-copy"><p className="eyebrow">LOVERTE X LAUREN</p><h2>Kohtume<br/>pühapäeval?</h2><p>Jäta meile oma nimi ja e-posti aadress.<br/>Ootame sind väga!</p><div className="practical"><p><span>MILLAL</span>4. oktoober · 11.00–14.00</p><p><span>KUS</span><a href="https://blessa.ee/" target="_blank" rel="noreferrer">Blessa Stuudio <ArrowUpRight size={16}/></a><small>Vesilennuki 20, Noblessner</small></p><p><span>DRESS CODE</span>Comfy casual — tule nii, et sul on hea.</p></div></div><div className="form-panel">{status==="success"?<div className="success" role="status"><span className="check"><Check size={28}/></span><h3>Sa oled kirjas!</h3><p>Kohtume 4. oktoobril kell 11.00<br/>Blessa Stuudios.</p><a className="button" href="/kbrunch.ics">Lisa kalendrisse <CalendarDays size={20}/></a></div>:<form onSubmit={submit}><h3>Jah, ma tulen!</h3><label htmlFor="name">Sinu nimi</label><input id="name" name="name" placeholder="Ees- ja perekonnanimi" autoComplete="name" required maxLength={100}/><label htmlFor="email">E-posti aadress</label><input id="email" name="email" type="email" placeholder="sinu@email.ee" autoComplete="email" required maxLength={254}/><label htmlFor="dietary">Toidueelistused või allergiad <span>(valikuline)</span></label><input id="dietary" name="dietary" placeholder="Et saaksime sinuga arvestada" maxLength={500}/><button className="button" disabled={status==="saving"}>{status==="saving"?"Kinnitame…":"Kinnitan osalemise"}<ArrowUpRight size={21}/></button>{status==="error"&&<p role="alert" className="error">Kinnitamine ei õnnestunud. Palun proovi uuesti.</p>}<p className="privacy">Kasutame sinu andmeid ainult selle ürituse korraldamiseks.</p></form>}</div></section><footer><a href="#" aria-label="Loverte"><img className="logo" src="/loverte-logo.png" alt="Loverte"/></a><span>LOVERTE X LAUREN · K-BRUNCH 2026</span></footer></main>}
